In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

iris = load_iris()

model = KNeighborsClassifier()

scores = cross_val_score(model, iris.data, iris.target, cv=5)

print("Scores:", scores)
print("Average Accuracy:", scores.mean())

Scores: [0.96666667 1.         0.93333333 0.96666667 1.        ]
Average Accuracy: 0.9733333333333334


In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

iris = load_iris()

model = DecisionTreeClassifier()

scores = cross_val_score(model, iris.data, iris.target, cv=10)

print("Accuracy for each fold:")
print(scores)

Accuracy for each fold:
[1.         0.93333333 1.         0.93333333 0.93333333 0.86666667
 0.93333333 1.         1.         1.        ]


In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
import numpy as np

iris = load_iris()
X, y = iris.data, iris.target

skf = StratifiedKFold(n_splits=5)

for i, (_, test_index) in enumerate(skf.split(X, y), 1):
    print("Fold", i)
    print(np.bincount(y[test_index]))

Fold 1
[10 10 10]
Fold 2
[10 10 10]
Fold 3
[10 10 10]
Fold 4
[10 10 10]
Fold 5
[10 10 10]


In [5]:
from sklearn.datasets import load_wine
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import numpy as np

wine = load_wine()

for cv in [3, 5, 10]:
    scores = cross_val_score(
        RandomForestClassifier(),
        wine.data,
        wine.target,
        cv=cv
    )

    print("cv =", cv)
    print("Mean =", scores.mean())
    print("Std =", scores.std())

cv = 3
Mean = 0.9607344632768361
Std = 0.02869978645681079
cv = 5
Mean = 0.9833333333333332
Std = 0.022222222222222233
cv = 10
Mean = 0.9833333333333332
Std = 0.02545875386086579


The cv value with the smallest standard deviation gives the most stable accuracy scores.

In [6]:
from sklearn.model_selection import cross_val_score
import numpy as np

def evaluate_model(model, X, y, k):
    scores = cross_val_score(model, X, y, cv=k)
    return scores.mean(), scores.std()

ChatGPT helped generate a reusable function that works with any classifier and dataset, reducing code duplication and making evaluation easier.