In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:


data = pd.DataFrame({
    'RAM':[4,6,8,12,16],
    'Storage':[64,128,256,256,512],
    'Battery':[4000,4500,5000,5000,6000],
    'Price':[10000,15000,22000,30000,45000]
})

X = data[['RAM','Storage','Battery']]
y = data['Price']

print(X)
print(y)

   RAM  Storage  Battery
0    4       64     4000
1    6      128     4500
2    8      256     5000
3   12      256     5000
4   16      512     6000
0    10000
1    15000
2    22000
3    30000
4    45000
Name: Price, dtype: int64


In [3]:
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=1)
lasso.fit(X,y)

print("Lasso Coefficients")
print(lasso.coef_)

Lasso Coefficients
[1985.50472401   37.23719125   -2.78635597]


In [4]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=1)
ridge.fit(X,y)

print("Ridge Coefficients")
print(ridge.coef_)

Ridge Coefficients
[1765.42273453   43.35771405   -2.83245754]


Lasso may set some coefficients to zero, effectively removing features, while Ridge keeps all coefficients but reduces their values.


In [5]:
from sklearn.linear_model import ElasticNet

elastic = ElasticNet(alpha=1,l1_ratio=0.5)
elastic.fit(X,y)

print("ElasticNet Coefficients")
print(elastic.coef_)

ElasticNet Coefficients
[1522.80409955   46.50657556   -2.05629669]


ElasticNet combines both L1 and L2 regularization, so its coefficients are usually between those of Lasso and Ridge.


In [6]:
print("Features Kept:")
for i in range(len(X.columns)):
    if lasso.coef_[i] != 0:
        print(X.columns[i])

print("\nFeatures Dropped:")
for i in range(len(X.columns)):
    if lasso.coef_[i] == 0:
        print(X.columns[i])

Features Kept:
RAM
Storage
Battery

Features Dropped:


Lasso regression kept all three features (RAM, Storage, and Battery) because their coefficients were non-zero. Therefore, no features were removed by the feature selection process.
