In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier

reviews = [
    "Good product",
    "Excellent quality",
    "Bad product",
    "Worst purchase",
    "Amazing phone",
    "Poor quality"
]

labels = ["positive","positive","negative","negative","positive","negative"]

cv = CountVectorizer()
X = cv.fit_transform(reviews)

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X, labels)

print(model.predict(cv.transform(["Good quality phone"])))

['positive']


In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

X = [[120,0.8,0.9],[90,0.4,0.3],[130,0.9,0.8],[85,0.3,0.2]]
y = ["workout","chill","workout","chill"]

# Fix: Set n_neighbors to a value less than or equal to the number of samples (4)
knn1 = KNeighborsClassifier(n_neighbors=3, metric="euclidean")
knn1.fit(X,y)

# Fix: Set n_neighbors to a value less than or equal to the number of samples (4)
knn2 = KNeighborsClassifier(n_neighbors=3, metric="manhattan")
knn2.fit(X,y)

print("Euclidean Accuracy:",accuracy_score(y,knn1.predict(X)))
print("Manhattan Accuracy:",accuracy_score(y,knn2.predict(X)))

Euclidean Accuracy: 1.0
Manhattan Accuracy: 1.0


In [5]:
from sklearn.naive_bayes import GaussianNB

X = [
    [10,9,1],
    [22,8,0],
    [18,3,1],
    [8,2,0]
]

y = ["confirmed","confirmed","waitlisted","waitlisted"]

model = GaussianNB()
model.fit(X,y)

print(model.predict([[12,8,1]]))

['confirmed']


In [6]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix

messages = [
    "Hi how are you",
    "Meeting at 5 pm",
    "Congratulations you won money",
    "Group project update",
    "Claim your prize now"
]

labels = ["personal","group","spam","group","spam"]

cv = CountVectorizer()
X = cv.fit_transform(messages)

model = MultinomialNB()
model.fit(X,labels)

pred = model.predict(X)

print(confusion_matrix(labels,pred))

[[2 0 0]
 [0 1 0]
 [0 0 2]]


In [7]:


X = np.random.rand(10,100)
y = ["bat"]*5 + ["football"]*5

model = KNeighborsClassifier()
model.fit(X,y)

test = np.random.rand(1,100)

print(model.predict(test))

['bat']


The AI-generated code worked with random pixel arrays instead of real images. No major changes were required, and the model successfully classified the test sample as either a cricket bat or a football.
